language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t crownkira/digitalace-frontend-test -f ./Dockerfile.dev .

script:
  - docker run -e CI=true crownkira/digitalace-frontend-test yarn run test
