# only used for testing
# built in travis ci environment
FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN yarn install
# copy over since this is not built from docker compose
# so not able to make use of volumes
COPY . .
CMD ["yarn", "start"]