// list(Permission.objects.values('id', 'codename'))
// TODO: limit permissions
export default [
  // { id: 1, codename: 'add_logentry' },
  // { id: 2, codename: 'change_logentry' },
  // { id: 3, codename: 'delete_logentry' },
  // { id: 4, codename: 'view_logentry' },
  // { id: 5, codename: 'add_permission' },
  // { id: 6, codename: 'change_permission' },
  // { id: 7, codename: 'delete_permission' },
  // { id: 8, codename: 'view_permission' },
  // { id: 9, codename: 'add_group' },
  // { id: 10, codename: 'change_group' },
  // { id: 11, codename: 'delete_group' },
  // { id: 12, codename: 'view_group' },
  // { id: 13, codename: 'add_contenttype' },
  // { id: 14, codename: 'change_contenttype' },
  // { id: 15, codename: 'delete_contenttype' },
  // { id: 16, codename: 'view_contenttype' },
  // { id: 17, codename: 'add_session' },
  // { id: 18, codename: 'change_session' },
  // { id: 19, codename: 'delete_session' },
  // { id: 20, codename: 'view_session' },
  // { id: 21, codename: 'add_token' },
  // { id: 22, codename: 'change_token' },
  // { id: 23, codename: 'delete_token' },
  // { id: 24, codename: 'view_token' },
  // { id: 25, codename: 'add_tokenproxy' },
  // { id: 26, codename: 'change_tokenproxy' },
  // { id: 27, codename: 'delete_tokenproxy' },
  // { id: 28, codename: 'view_tokenproxy' },
  { id: 29, codename: 'add_user' },
  { id: 30, codename: 'change_user' },
  { id: 31, codename: 'delete_user' },
  { id: 32, codename: 'view_user' },
  { id: 33, codename: 'add_company' },
  { id: 34, codename: 'change_company' },
  { id: 35, codename: 'delete_company' },
  { id: 36, codename: 'view_company' },
  { id: 37, codename: 'add_userconfig' },
  { id: 38, codename: 'change_userconfig' },
  { id: 39, codename: 'delete_userconfig' },
  { id: 40, codename: 'view_userconfig' },
  { id: 41, codename: 'add_department' },
  { id: 42, codename: 'change_department' },
  { id: 43, codename: 'delete_department' },
  { id: 44, codename: 'view_department' },
  { id: 45, codename: 'add_role' },
  { id: 46, codename: 'change_role' },
  { id: 47, codename: 'delete_role' },
  { id: 48, codename: 'view_role' },
  { id: 49, codename: 'add_supplier' },
  { id: 50, codename: 'change_supplier' },
  { id: 51, codename: 'delete_supplier' },
  { id: 52, codename: 'view_supplier' },
  { id: 53, codename: 'add_productcategory' },
  { id: 54, codename: 'change_productcategory' },
  { id: 55, codename: 'delete_productcategory' },
  { id: 56, codename: 'view_productcategory' },
  { id: 57, codename: 'add_customer' },
  { id: 58, codename: 'change_customer' },
  { id: 59, codename: 'delete_customer' },
  { id: 60, codename: 'view_customer' },
  { id: 61, codename: 'add_product' },
  { id: 62, codename: 'change_product' },
  { id: 63, codename: 'delete_product' },
  { id: 64, codename: 'view_product' },
  { id: 65, codename: 'add_invoice' },
  { id: 66, codename: 'change_invoice' },
  { id: 67, codename: 'delete_invoice' },
  { id: 68, codename: 'view_invoice' },
  { id: 69, codename: 'add_salesorder' },
  { id: 70, codename: 'change_salesorder' },
  { id: 71, codename: 'delete_salesorder' },
  { id: 72, codename: 'view_salesorder' },
  { id: 73, codename: 'add_salesorderitem' },
  { id: 74, codename: 'change_salesorderitem' },
  { id: 75, codename: 'delete_salesorderitem' },
  { id: 76, codename: 'view_salesorderitem' },
  { id: 77, codename: 'add_invoiceitem' },
  { id: 78, codename: 'change_invoiceitem' },
  { id: 79, codename: 'delete_invoiceitem' },
  { id: 80, codename: 'view_invoiceitem' },
  { id: 81, codename: 'add_purchaseorder' },
  { id: 82, codename: 'change_purchaseorder' },
  { id: 83, codename: 'delete_purchaseorder' },
  { id: 84, codename: 'view_purchaseorder' },
  { id: 85, codename: 'add_receive' },
  { id: 86, codename: 'change_receive' },
  { id: 87, codename: 'delete_receive' },
  { id: 88, codename: 'view_receive' },
  { id: 89, codename: 'add_receiveitem' },
  { id: 90, codename: 'change_receiveitem' },
  { id: 91, codename: 'delete_receiveitem' },
  { id: 92, codename: 'view_receiveitem' },
  { id: 93, codename: 'add_purchaseorderitem' },
  { id: 94, codename: 'change_purchaseorderitem' },
  { id: 95, codename: 'delete_purchaseorderitem' },
  { id: 96, codename: 'view_purchaseorderitem' },
  { id: 97, codename: 'add_payslip' },
  { id: 98, codename: 'change_payslip' },
  { id: 99, codename: 'delete_payslip' },
  { id: 100, codename: 'view_payslip' },
  { id: 101, codename: 'add_stockbalance' },
  { id: 102, codename: 'change_stockbalance' },
  { id: 103, codename: 'delete_stockbalance' },
  { id: 104, codename: 'view_stockbalance' },
  { id: 105, codename: 'add_designation' },
  { id: 106, codename: 'change_designation' },
  { id: 107, codename: 'delete_designation' },
  { id: 108, codename: 'view_designation' },
];
